@CaseySmartHub.Api_HostAddress = http://localhost:5156

### Get all benches/seats from Casey Open Data
GET {{CaseySmartHub.Api_HostAddress}}/api/GetBenches
Accept: application/json

### Get all drinking fountains from Casey Open Data
GET {{CaseySmartHub.Api_HostAddress}}/api/GetDrinkingFountains
Accept: application/json

###
