services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: casey-frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: casey-backend
    ports:
      - "5156:8080"