import { Amenity, FilterOption, FitnessGoal, Places, Walk } from "@/src/types/walkPlannerTypes";

export const MY_WALKS: Walk[] = [
  {
    id: 'w1',
    title: 'Testing Walk Func',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 2.4,
    durationMin: 32,
    difficulty: 'Easy',
    tags: ['Park', 'Waterway'],
    thumbnailColor: '#C8E6C9',
    rating: 4.7,
    reviewCount: 128,
    isFavorited: true,
    isCompleted: false,
    routeId: 'bbq-walk',
  },
  {
    id: 'w2',
    title: 'Beautiful Walk 2',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 5.1,
    durationMin: 68,
    difficulty: 'Moderate',
    tags: ['Hills', 'Scenic'],
    thumbnailColor: '#B2DFDB',
    rating: 4.3,
    reviewCount: 84,
    isFavorited: false,
    isCompleted: true,
  },
  {
    id: 'w3',
    title: 'Beautiful Walk 3',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 1.8,
    durationMin: 24,
    difficulty: 'Easy',
    tags: ['Flat', 'Family'],
    thumbnailColor: '#DCEDC8',
    rating: 4.9,
    reviewCount: 210,
    isFavorited: true,
    isCompleted: false,
  },
    {
    id: 'w4',
    title: 'Beautiful Walk 3',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 1.8,
    durationMin: 24,
    difficulty: 'Easy',
    tags: ['Flat', 'Family'],
    thumbnailColor: '#DCEDC8',
    rating: 4.9,
    reviewCount: 210,
    isFavorited: true,
    isCompleted: false,
  },
    {
    id: 'w5',
    title: 'Beautiful Walk 3',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 1.8,
    durationMin: 24,
    difficulty: 'Easy',
    tags: ['Flat', 'Family'],
    thumbnailColor: '#DCEDC8',
    rating: 4.9,
    reviewCount: 210,
    isFavorited: true,
    isCompleted: false,
  },
    {
    id: 'w6',
    title: 'Beautiful Walk 3',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 1.8,
    durationMin: 24,
    difficulty: 'Easy',
    tags: ['Flat', 'Family'],
    thumbnailColor: '#DCEDC8',
    rating: 4.9,
    reviewCount: 210,
    isFavorited: true,
    isCompleted: false,
  },
    {
    id: 'w7',
    title: 'Beautiful Walk 3',
    subtitle: 'Suburb Walk, VIC, 3000',
    distanceKm: 1.8,
    durationMin: 24,
    difficulty: 'Easy',
    tags: ['Flat', 'Family'],
    thumbnailColor: '#DCEDC8',
    rating: 4.9,
    reviewCount: 210,
    isFavorited: true,
    isCompleted: false,
  },
];

// Real Casey-area lake/wetland loops, coordinates approximated around each lake's centre point.
// See mapRouting.ts for the matching routeId geometry drawn on the map.
export const COMMUNITY_WALKS: Walk[] = [
  {
    id: 'cw1',
    title: 'Marriott Waters Circuit',
    subtitle: 'Lyndhurst, VIC 3975',
    distanceKm: 4.0,
    durationMin: 60,
    difficulty: 'Easy',
    tags: ['Lake', 'Flat', 'Family'],
    thumbnailColor: '#B3E5FC',
    downloads: 37,
    routeId: 'marriott-waters-loop',
  },
  {
    id: 'cw2',
    title: 'Berwick Springs Circuit',
    subtitle: 'Narre Warren South, VIC 3805',
    distanceKm: 5.0,
    durationMin: 75,
    difficulty: 'Easy',
    tags: ['Wetlands', 'Birdwatching', 'Boardwalk'],
    thumbnailColor: '#A5D6A7',
    downloads: 48,
    routeId: 'berwick-springs-loop',
  },
  {
    id: 'cw3',
    title: 'Casey Fields Lakeside Circuit',
    subtitle: 'Cranbourne East, VIC 3977',
    distanceKm: 3.7,
    durationMin: 55,
    difficulty: 'Easy',
    tags: ['Lake', 'Gravel Path', 'Sporting Precinct'],
    thumbnailColor: '#81D4FA',
    downloads: 22,
    routeId: 'casey-fields-lake-loop',
  },
];

export const FITNESS_GOALS: FitnessGoal[] = [
  {
    id: 'g1',
    label: 'Weekly Distance',
    unit: 'km',
    current: 14,
    target: 20
  },
  {
    id: 'g2',
    label: 'Daily Steps',
    unit: 'steps',
    current: 7800,
    target: 10000
  },
];

export const FILTER_OPTIONS: FilterOption[] = [
  { id: 'f1', label: 'Scenic Waterway', type: 'Scenic Waterway' },
  { id: 'f2', label: 'Grebe Park', type: 'Grass Park' },
  { id: 'f3', label: 'Scenic Amenities', type: 'Scenic Amenities' },
  { id: 'f4', label: 'Sports Facilities', type: 'Sports Facilities' },
  { id: 'f5', label: 'Scenic Fun', type: 'Scenic Fun' },
];

export const PLACES: Places[] = [
  {
    id: 'p1',
    title: 'Coles',
    streetAddress: '100 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p2',
    title: 'Woolies',
    streetAddress: '11 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p3',
    title: 'Aldi',
    streetAddress: '12 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p4',
    title: 'Casey Park',
    streetAddress: '13 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p5',
    title: 'Skate Park',
    streetAddress: '14 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p6',
    title: 'Maternity Center',
    streetAddress: '15 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p7',
    title: 'Casey Hospital',
    streetAddress: '16 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
  {
    id: 'p8',
    title: 'Toilet',
    streetAddress: '17 Chirag Place',
    suburb: 'Casey',
    state: 'Victoria',
    country: 'Australia',
  },
]